name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4 scrapy gitpython openai

    - name: Run tests
      run: |
        # test
        python -m unittest discover

    - name: Lint with flake8
      run: |
        # Lint the codebase
        pip install flake8
        flake8 .
